name: Google Sheet Update
on:
  pull_request_target:
    types: [closed]

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: 'get all added files in the PR'
        if: github.event.pull_request.merged == true
        id: 'files'
        uses: mmagician/get-changed-files@v0.0.1

      - uses: actions/checkout@master
        if: github.event.pull_request.merged == true
        name: Checkout

      - name: 'parse files'
        if: github.event.pull_request.merged == true
        id: grant_parser
        uses: mmagician/read-file-action@master
        with:
          path: "${{ steps.files.outputs.added }}"
          # path: 'applications/sup.md'

      - name: Pull Request URL
        if: github.event.pull_request.merged == true
        id: pr_link_parser
        uses: kceb/pull-request-url-action@v1
        with:
          github-oauth-token: ${{ secrets.GITHUB_TOKEN }}

      # local testing only
      # - name: Pull Request URL
      #   id: pr_link_parser
      #   run: echo "::set-output name=date::$(date +'%d/%m/%Y')"}

      - name: Get current date
        if: github.event.pull_request.merged == true
        id: date
        run: echo "::set-output name=date::$(date +'%d/%m/%Y')"

      - name: Get last row
        if: github.event.pull_request.merged == true
        id: get_last_row
        uses: mmagician/gsheet.action@v0.1.0
        with:
          spreadsheetId: 1m0I_spkPkLaI8fXCDGTKC1R_fSCaWK4vcnQQsIvwHDo
          startRow: 196
          worksheetTitle: "Legal"
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

      - name: 'write the data to a gsheet'
        if: github.event.pull_request.merged == true
        id: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.0.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: 1m0I_spkPkLaI8fXCDGTKC1R_fSCaWK4vcnQQsIvwHDo
          commands: | # list of commands, specified as a valid JSON string
            [
              { 
                "command": "updateData", 
                "args": 
                { 
                  "data": [[
                    "${{ steps.grant_parser.outputs.team_name }}", 
                    "${{ steps.grant_parser.outputs.team_name }}", 
                    "Open Grants",
                    "${{ steps.grant_parser.outputs.project_name }}", 
                    "${{ steps.grant_parser.outputs.address }}", 
                    "${{ steps.grant_parser.outputs.contact_name }}", 
                    "${{ steps.grant_parser.outputs.contact_name }}", 
                    "${{ steps.grant_parser.outputs.contact_title }}", 
                    "${{ steps.grant_parser.outputs.contact_email }}", 
                    "${{ steps.grant_parser.outputs.country }}", 
                    "",
                    "${{ steps.pr_link_parser.outputs.url }}", 
                    "${{ steps.pr_link_parser.outputs.url }}",
                    "USD", "0", "0", "0",
                    "${{ steps.pr_link_parser.outputs.total_cost }}",
                    "", "",
                    "Executed",
                    "${{ steps.pr_link_parser.outputs.url }}",
                    "${{ steps.date.outputs.date }}"
                  ]], 
                  "worksheetTitle": "Legal", 
                  "minCol": 1,
                  "minRow": "${{ steps.get_last_row.outputs.lastRow }}",
                  "valueInputOption": "USER_ENTERED"
                }
               }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
